language: python
python:
  - "3.7"

  
# command to install dependencies
install:
  - pip install --upgrade pip   
  - pip install git+https://github.com/dxc-technology/DXC-Industrialized-AI-Starter.git
  
script: pytest -v -s
