language: python
python:
  - "3.7"
  
# command to install dependencies
install:
#   - pip install git+https://github.com/dxc-technology/DXC-Industrialized-AI-Starter.git
  - pip install git+https://github.com/madhubandru/DXC-Industrialized-AI-Starter.git
  - conda install --yes numpy=1.8
script: pytest -v -s
