name: Project Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools pip
          pip install -r requirements.txt
          pip install git+https://github.com/dxc-technology/DXC-Industrialized-AI-Starter.git
      - name: Test with pytest
        env: 
          MONGODB_ID: ${{ secrets.MONGODB_ID }}
          MONGODB_PWD: ${{ secrets.MONGODB_PWD }}
          MICROSERVICE_USERNAME: ${{ secrets.MICROSERVICE_USERNAME }}
          MICROSERVICE_KEY: ${{ secrets.MICROSERVICE_KEY }}
        run: pytest -v -s
